In [1]:
#Que1 . What is a Python library? Why ^o we use Python libraries?
'''
A Python library is a collection of related modules that contain bundles of code that can be used in different programs. Python libraries are used to
create applications and models in a variety of fields, such as machine learning, data science, data visualization, and image and data manipulation.
Python libraries provide a wide range of functionalities, such as: Data manipulation, Scientific computing, Web development, Machine learning.
Python libraries make it easier for developers to work on specific tasks without reinventing the wheel. They help developers to build robust and efficient
applications by using the existing code and tools provided by the library.
'''

'\nA Python library is a collection of related modules that contain bundles of code that can be used in different programs. Python libraries are used to\ncreate applications and models in a variety of fields, such as machine learning, data science, data visualization, and image and data manipulation.\nPython libraries provide a wide range of functionalities, such as: Data manipulation, Scientific computing, Web development, Machine learning. \nPython libraries make it easier for developers to work on specific tasks without reinventing the wheel. They help developers to build robust and efficient \napplications by using the existing code and tools provided by the library. \n'

In [2]:
#Que2 What is the difference between Numpy array and List?
'''
Numpy ->
1 Broadcasting:
NumPy arrays support broadcasting, which allows you to perform operations on arrays of different shapes.

2 Optimized:
NumPy arrays are optimized for numerical operations, such as linear algebra and calculus.

3 Efficient:
NumPy arrays are more memory-efficient than Python lists, especially when working with large datasets.

4 Homogeneous:
All elements in a NumPy array must be of the same data type

List ->
1 Heterogeneous: Python lists can contain elements of different data types.
2 Flexible: Python lists are more flexible than NumPy arrays, as you can add, remove, and modify elements at any time.
3 Slower: Python lists are slower than NumPy arrays for numerical operations.
4 No broadcasting: Python lists do not support broadcasting.
'''


'\nNumpy ->\n1 Broadcasting:\nNumPy arrays support broadcasting, which allows you to perform operations on arrays of different shapes.\n\n2 Optimized:\nNumPy arrays are optimized for numerical operations, such as linear algebra and calculus.\n\n3 Efficient:\nNumPy arrays are more memory-efficient than Python lists, especially when working with large datasets.\n\n4 Homogeneous:\nAll elements in a NumPy array must be of the same data type\n\nList ->\n1 Heterogeneous: Python lists can contain elements of different data types.\n2 Flexible: Python lists are more flexible than NumPy arrays, as you can add, remove, and modify elements at any time.\n3 Slower: Python lists are slower than NumPy arrays for numerical operations.\n4 No broadcasting: Python lists do not support broadcasting.\n'

In [5]:
'''
Que3
3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
'''
import numpy as np
arr=np.asarray([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print("Shape :",arr.shape)
print("Size :",arr.size)
print("Dimension :",arr.ndim)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape : (3, 4)
Size : 12
Dimension : 2


In [6]:
'''
Que4 Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
'''
arr=np.asarray([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("First Row :",arr[0])

First Row : [1 2 3 4]


In [7]:
'''
Que5 How to you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
'''
arr=np.asarray([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[2][3])

12


In [17]:
'''
Que6 Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
'''
arr=np.asarray([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[0:,[1,3]])


[[ 2  4]
 [ 6  8]
 [10 12]]


In [13]:
'''
Que7  How can you generate a random 3x3 matrix with values between 0 and 1?
'''
print(np.random.rand(3,3))

[[0.01020339 0.41067982 0.12889259]
 [0.5749923  0.74092819 0.88133064]
 [0.7255043  0.01673352 0.74355282]]


In [20]:
'''
Que8 Describe the difference between np.random.rand and np.random.randint?
1 np.random.rand -
The np.random.rand function generates random numbers from a uniform distribution on the interval [0, 1]. This means that each number generated by the
function has an equal probability of being any value between 0 and 1. The function takes one argument, which is the size of the output array.
The output array will be a 1D array of random numbers.

2 np.random.randint-
The np.random.randint function generates random integers from a specified range. The function takes two arguments, which are the lower and upper bounds of
the range. The output array will be a 1D array of random integers between the lower and upper bounds, inclusive.
'''
#Example -
print(np.random.rand(5,3))
print(np.random.randint(1,5,(3,3)))

[[0.71685383 0.84841851 0.60879147]
 [0.72007898 0.7113231  0.30963013]
 [0.12275136 0.66528791 0.34836285]
 [0.67251108 0.85865087 0.91148676]
 [0.44942932 0.23239209 0.39284845]]
[[2 2 1]
 [3 1 4]
 [2 2 3]]


In [25]:
'''
Que9 Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
'''
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.ndim)
print(np.expand_dims(arr,axis=0))
print(np.expand_dims(arr,axis=1))
print(np.expand_dims(arr,axis=1))



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


In [26]:
'''
Que10 How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
'''
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [32]:
'''
11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python
'''
# 1 indexed wise multiplication
arr1=np.asarray([[1,2,3,4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr2=np.asarray([[1,2,3,4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr1*arr2)

# 2 Matrix multiplication
print(arr1 @ arr2)
# 3 Add both matrix
print(arr1+arr2)

# 4 Divide arr2 by arr1
print(arr2//arr1)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [39]:
'''
#Que12 Which function in Numpy can be use^ to swap the byte or^er of an array?
The byteswap() function in NumPy can be used to swap the byte order of an array. The syntax is:
'''
arr = np.array([1, 2, 3, 4], dtype=np.int32)

original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Display the original array
print("Original array:", original_array)

# Byteswap the array
swapped_array = original_array.byteswap()

# Display the swapped array
print("Byteswapped array:", swapped_array)

Original array: [1 2 3 4]
Byteswapped array: [16777216 33554432 50331648 67108864]


In [35]:
'''
Que13 What is the significance of the np.linalg.inv function?
The np.linalg.inv function is a function in the NumPy library that calculates the inverse of a matrix. The inverse of a matrix is a matrix that, when
multiplied by the original matrix, results in the identity matrix. The identity matrix is a square matrix with ones on the diagonal and zeros everywhere else.
The np.linalg.inv function is significant because it can be used to solve a variety of problems in linear algebra. For example, it can be used to solve
systems of linear equations, to find the eigenvalues and eigenvectors of a matrix, and to compute the determinant of a matrix.
'''
A = np.array([[2, 1], [4, 3]])
B = np.array([1, 2])
x = np.linalg.inv(A).dot(B)

print()


[0.5 0. ]


In [34]:
'''
Que14 What does the np.reshape function do, and how is it used?
The np.reshape function in Python is used to change the shape of a NumPy array. It takes two arguments: the array to be reshaped and the new shape. The new
shape can be a tuple of integers or a single integer. If the new shape is a tuple of integers, then the array will be reshaped to have the specified dimensions. If the new shape is a single integer, then the array will be reshaped to have a single dimension with the specified length.
'''
arr = np.array([1, 2, 3, 4, 5,6])
print(np.reshape(arr,(2,3)))

[[1 2 3]
 [4 5 6]]


In [ ]:
'''
Que15 What is broadcasting in Numpy?
Broadcasting can be used with any arithmetic operation, including addition, subtraction, multiplication, and division. It can also be used with comparison
operators, such as >, <, ==, and !=.Broadcasting is a powerful feature that can be used to simplify many NumPy operations. It is important to understand how
broadcasting works in order to use NumPy effectively.Broadcasting is a powerful NumPy feature that allows arrays of different shapes to be used in operations
together. This is done by automatically expanding the smaller array to match the shape of the larger array.
'''